[package]
name = "duckengine-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.11.2", features = ["lua54"] }
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.14"
toml = "0.9.5"
