[package]
name = "duckengine-script-lua"
version = "0.1.0"
edition = "2024"

[dependencies]
duckengine-core = { path = "../duckengine-core" }
env_logger = "0.11.8"
log = "0.4.27"
thiserror = "2.0.16"
